#server:
#  port: 9528
#
#spring:
#  application:
#    name: client-gateway-client
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    gateway:
#      routes:
#        - id: user_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
#          predicates:
#            - Path=/user/**   #断言，路径相匹配的进行路由
#
#        - id: system_routh
#          uri: lb://cloud-admin-system
#          predicates:
#            - Path=/system/**